Leave slash command update while testing
Promact/slack-erp-custom-integration-mvc pull request #115
Opened 2016-11-29 10:17 UTC by siddharthashw

1. Client.cs - Changes in the stringConstant declaration, added logic for selecting a different template for sick leave/casual leave and added a method to generate sick leave template.
2. SlackRepository.cs - Change the logic of getting user details from name to their id. And updated leave list and leave status reply text.
3. SickLeaveApplication.cs   - Newly added for sick leave template.
4. SickLeaveApplication.tt - Newly added for sick leave template.
5. StringConstantRepository.cs - Change in date format and change in leave command help message. And added new variables
6. SlackRepositoryTest.cs - Change done in the test case as per SlackRepository.cs., Update leave list and leave status test case. And added new test cases for some more scenario.

2016-12-05 11:43 UTC, chintans requested changes
Overall too many changes. I have not reviewed every single detail yet but there are many points besides my comments. please fix all and re-submit.

2016-12-05 11:43 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/Client/Client.cs
>          private readonly IEmailService _email;
naming convention is wrong. _email is not a meaningful name

2016-12-05 11:43 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/ExternalLoginRepository/OAuthLoginRepository.cs
> +        public OAuthApplication ExternalLoginInformationAsync(string refreshToken)
this method is not async then why it is marked as Async?

2016-12-05 11:43 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/SlackRepository/SlackRepository.cs
> +            replyText = string.Format("You had {0} Leave for {1} From {2} To {3} for Reason {4} will re-join by {5}",
should be in stringConstants

2016-12-05 11:43 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/SlackRepository/SlackRepository.cs
> +            _client.UpdateMessageAsync(leaveResponse, replyText);
this method is async and should be awaited. the parent method is not marked as async too

2016-12-05 11:43 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/SlackRepository/SlackRepository.cs
>          private async Task<string> LeaveList(string slackUserId, string accessToken)
naming is wrong

2016-12-05 11:43 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/SlackRepository/SlackRepository.cs
>          private async Task<string> CancelLeave(int leaveId, string slackUserId, string accessToken)
wrong naming

2016-12-05 11:43 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/SlackRepository/SlackRepository.cs
> +                    replyText = string.Format("Casual leave Id no: {0} From {1} To {2} for {3} is {4}", leave.Id, leave.FromDate.ToShortDateString(), leave.EndDate.Value.ToShortDateString(), leave.Re
should be in stringConstants

2016-12-05 11:43 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/SlackRepository/SlackRepository.cs
>          private async Task<string> SlackLeaveCancel(List<string> slackText, SlashCommand leave, string accessToken)
naming issue

2016-12-05 11:43 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/SlackRepository/SlackRepository.cs
> +                replyText += string.Format("{2}You have taken {0} sick leave out of {1}{2}You have sick leave left {3}", sickLeaveTaken, allowedLeave.SickLeave, Environment.NewLine, sickLeaveLeft);
should be in stringConstants

2016-12-05 11:43 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/SlackRepository/SlackRepository.cs
>          private async Task<string> UpdateSickLeave(List<string> slackText, ApplicationUser user, string accessToken)
naming issue

2016-12-05 11:43 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
>                  foreach (var j in json)
Wrong naming convention

2016-12-05 11:43 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +                var json = await _oauthCallsRepository.GetListOfEmployeeAsync(user.Id, accessToken);
what is the meaning of json? should be some meaningful name

2016-12-05 11:43 UTC, chintans commented on Slack.Automation/Promact.Erp.Core/Controllers/OAuthController.cs
>          public IHttpActionResult RefreshToken(string refreshToken, string slackUserName)
this action should be async

2016-12-05 11:43 UTC, chintans commented on Slack.Automation/Promact.Erp.Core/Controllers/TaskReportController.cs
>          public async Task<List<TaskMailUserAc>> TaskMailDetailsReport(string UserId,string UserRole,string UserName)
naming issue

2016-12-05 11:43 UTC, chintans commented on Slack.Automation/Promact.Erp.Core/Controllers/TaskReportController.cs
>          public async Task<List<TaskMailUserAc>> TaskMailDetailsReportSelectedDate(string UserRole, string CreatedOn, string UserId, string UserName,string SelectedDate)
naming issue

2016-12-05 11:43 UTC, chintans commented on Slack.Automation/Promact.Erp.Core/Controllers/TaskReportController.cs
>          public async Task<List<TaskMailUserAc>> getAllEmployee()
naming issue

2016-12-05 11:43 UTC, chintans commented on Slack.Automation/Promact.Erp.Util/Email Templates/LeaveApplication.cs
> +            this.Write("\n");
not sure what is the purpose of this?

2016-12-05 11:43 UTC, chintans commented on Slack.Automation/Promact.Erp.Util/Email Templates/LeaveApplication.cs
> +            #line 15 "F:\Siddhartha\slack-automation\slack-erp-custom-integration-mvc\Slack.Automation\Promact.Erp.Util\Email Templates\LeaveApplication.tt"
not sure why hardcoded path is given?

2016-12-05 11:43 UTC, chintans commented on Slack.Automation/Promact.Erp.Util/HttpClient/HttpClientService.cs
> +            catch (Exception ex)
Why are you catching a generic exception here?

2016-12-05 12:11 UTC, siddharthashw commented on Slack.Automation/Promact.Erp.Util/Email Templates/LeaveApplication.cs
> +            this.Write("\n");
Used to create template to be sent from leave application

2016-12-05 12:40 UTC, siddharthashw commented on Slack.Automation/Promact.Erp.Util/Email Templates/LeaveApplication.cs
> +            #line 15 "F:\Siddhartha\slack-automation\slack-erp-custom-integration-mvc\Slack.Automation\Promact.Erp.Util\Email Templates\LeaveApplication.tt"
Don't know why it's showing hard coded but literally, I didn't.

2016-12-05 12:47 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/Client/Client.cs
>          private readonly IEmailService _email;
Update from _email to _emailService

2016-12-05 12:47 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/ExternalLoginRepository/OAuthLoginRepository.cs
> +        public OAuthApplication ExternalLoginInformationAsync(string refreshToken)
Unmarked as not Async

2016-12-05 12:53 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/SlackRepository/SlackRepository.cs
> +            _client.UpdateMessageAsync(leaveResponse, replyText);
Updated the method as well as parent method too

2016-12-06 06:15 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/SlackRepository/SlackRepository.cs
> +            replyText = string.Format("You had {0} Leave for {1} From {2} To {3} for Reason {4} will re-join by {5}",
Shifted in stringConstant

2016-12-06 06:15 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/SlackRepository/SlackRepository.cs
> +                    replyText = string.Format("Casual leave Id no: {0} From {1} To {2} for {3} is {4}", leave.Id, leave.FromDate.ToShortDateString(), leave.EndDate.Value.ToShortDateString(), leave.Re
Shifted in stringConstant

2016-12-06 06:15 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/SlackRepository/SlackRepository.cs
> +                replyText += string.Format("{2}You have taken {0} sick leave out of {1}{2}You have sick leave left {3}", sickLeaveTaken, allowedLeave.SickLeave, Environment.NewLine, sickLeaveLeft);
Shifted in stringConstant

2016-12-06 06:22 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +                var json = await _oauthCallsRepository.GetListOfEmployeeAsync(user.Id, accessToken);
This part is belong to @iamronakshah . So he had made changes in his issue #122 .

2016-12-06 06:22 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
>                  foreach (var j in json)
This part is belong to @iamronakshah . So he had made changes in his issue #122 .

2016-12-06 06:22 UTC, siddharthashw commented on Slack.Automation/Promact.Erp.Core/Controllers/TaskReportController.cs
>          public async Task<List<TaskMailUserAc>> TaskMailDetailsReport(string UserId,string UserRole,string UserName)
This part is belong to @iamronakshah . So he had made changes in his issue #122 .

2016-12-06 06:22 UTC, siddharthashw commented on Slack.Automation/Promact.Erp.Core/Controllers/TaskReportController.cs
>          public async Task<List<TaskMailUserAc>> TaskMailDetailsReportSelectedDate(string UserRole, string CreatedOn, string UserId, string UserName,string SelectedDate)
This part is belong to @iamronakshah . So he had made changes in his issue #122 .

2016-12-06 06:22 UTC, siddharthashw commented on Slack.Automation/Promact.Erp.Core/Controllers/TaskReportController.cs
>          public async Task<List<TaskMailUserAc>> getAllEmployee()
This part is belong to @iamronakshah . So he had made changes in his issue #122 .

2016-12-06 06:40 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/SlackRepository/SlackRepository.cs
>          private async Task<string> LeaveList(string slackUserId, string accessToken)
Updated Naming

2016-12-06 06:40 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/SlackRepository/SlackRepository.cs
>          private async Task<string> CancelLeave(int leaveId, string slackUserId, string accessToken)
Updated Naming

2016-12-06 06:40 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/SlackRepository/SlackRepository.cs
>          private async Task<string> SlackLeaveCancel(List<string> slackText, SlashCommand leave, string accessToken)
Updated Naming

2016-12-06 06:41 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/SlackRepository/SlackRepository.cs
>          private async Task<string> UpdateSickLeave(List<string> slackText, ApplicationUser user, string accessToken)
Updated Naming

2016-12-06 06:48 UTC, siddharthashw commented on Slack.Automation/Promact.Erp.Util/HttpClient/HttpClientService.cs
> +            catch (Exception ex)
For Exception Handling in HttpClientService, @juliepromact is working on it.

2016-12-06 06:54 UTC, siddharthashw commented on Slack.Automation/Promact.Erp.Core/Controllers/OAuthController.cs
>          public IHttpActionResult RefreshToken(string refreshToken, string slackUserName)
Updated action to async

2016-12-10 09:57 UTC, chintans requested changes

2016-12-10 09:57 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/Client/Client.cs
> +        public async Task UpdateMessageAsync(string responseUrl, string replyText, string slackUserName)
comment needs to be updated as per parameter

2016-12-10 09:57 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/Client/Client.cs
> +            var textJson = JsonConvert.SerializeObject(text);
not sure what text and textJson means. should have meaningful name

2016-12-10 09:57 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/Client/Client.cs
> +        public async Task SendMessageAsync(string responseUrl, string replyText)
comment not updated. same issue as above. naming is not meaningful

2016-12-10 09:57 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/Client/Client.cs
> +        public async Task SendMessageWithAttachmentIncomingWebhookAsync(LeaveRequest leaveRequest, string accessToken, string replyText, string username, string slackUserId)
comment needs to be updated

2016-12-10 09:57 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/ScrumRepository/ScrumBotRepository.cs
> +            string status = await ExpectedUser(scrumId, questions, employees, applicant,applicantId);//checks whether the applicant is the expected user
ExpectedUser should be async

2016-12-12 05:45 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/Client/Client.cs
> +        public async Task UpdateMessageAsync(string responseUrl, string replyText, string slackUserName)
Comment updated

2016-12-12 05:46 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/Client/Client.cs
> +            var textJson = JsonConvert.SerializeObject(text);
updated with meaningful name

2016-12-12 05:46 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/Client/Client.cs
> +        public async Task SendMessageAsync(string responseUrl, string replyText)
Comment updated

2016-12-12 05:46 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/Client/Client.cs
> +        public async Task SendMessageWithAttachmentIncomingWebhookAsync(LeaveRequest leaveRequest, string accessToken, string replyText, string username, string slackUserId)
Comment updated

2016-12-12 05:47 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/ScrumRepository/ScrumBotRepository.cs
> +            string status = await ExpectedUser(scrumId, questions, employees, applicant,applicantId);//checks whether the applicant is the expected user
Scrum bot is not my part. @juliepromact will update

2016-12-13 12:01 UTC, chintans approved these changes

2016-12-13 12:02 UTC, merged