Refactor task mail module
Promact/slack-erp-custom-integration-mvc pull request #122
Opened 2016-12-01 08:35 UTC by iamronakshah

Fixed #105 

Files Changed:
ITaskMailRepository.cs : Improved naming convention  
TaskMailRepository.cs : Improved naming convention , Improved use async await and remove used repetitive code 
TaskMailRepositoryTest.cs : Improved naming convention and added new testcases. 
TaskReportController.cs : Improved Route,naming convention and apidoc 
TaskMailDetailReportAc.cs : Added TaskMailDetailReport Application class
TaskMailReportAc.cs : Updated TaskMailReport Application class
TaskMailUserAc.cs : Remove TaskMailUser Application class
UserRoleAc.cs : Updated UserRole Application Class
IStringConstantRepository.cs : Added new string constant
StringConstantRepository.cs : Added new string constant
mock.taskmailReport.service.ts :  Improved variable naming convention 
stringConstant.ts : Added new string constant
taskmail-details.component.ts : Improved variable naming convention 
taskmail.service.ts : Improved Routes.
taskmailuser.model.ts : improve naming convention

2016-12-26 10:53 UTC, chintans requested changes

2016-12-26 10:53 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/ITaskMailRepository.cs
> +        Task<List<TaskMailReportAc>> TaskMailDetailsReportAsync(string id,string role,string name,string loginId);
naming inconsistency, in one of the previous method you named it userId and here userId.

2016-12-26 10:53 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/ITaskMailRepository.cs
> +        Task<List<TaskMailReportAc>> GetAllEmployeeAsync(string id);
Since you are getting the list of all employees here why are you passing id here? what does id refer it to?

2016-12-26 10:53 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +        DateTime? maxDate = null;
why have you declared this variables as global?

2016-12-26 12:57 UTC, iamronakshah commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/ITaskMailRepository.cs
> +        Task<List<TaskMailReportAc>> TaskMailDetailsReportAsync(string id,string role,string name,string loginId);
I have improve naming conversion.

2016-12-26 12:59 UTC, iamronakshah commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/ITaskMailRepository.cs
> +        Task<List<TaskMailReportAc>> GetAllEmployeeAsync(string id);
for identifying login user role.
based on that I have to decide which view to show to end user.
like if role is "Admin" then show list of employees.

2016-12-26 13:00 UTC, iamronakshah commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +        DateTime? maxDate = null;
now I have removed global variables.

2016-12-27 10:07 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
>          string questionText = "";
why is this variable here still?

2016-12-27 10:07 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/ITaskMailRepository.cs
> +        Task<List<TaskMailReportAc>> GetAllEmployeeAsync(string id);
It is not clear from name. what is the purpose of GetAllEmployees. It looks like it returns all employees. Please improve naming.

2016-12-27 10:22 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
>          string questionText = "";
It is used in two methods and used for storing the question statement. And **questionText** is changable for every request. That why used it as global.
Methods - StartTaskMailAsync and QuestionAndAnswerAsync

2016-12-27 10:32 UTC, chintans requested changes
TaskMailRepository needs a lots of optimization. Please go through the code again and fix all the issues before resubmitting pull request. I have not commented all the issues in this review because there are so many of them.

2016-12-27 10:32 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +                                                nextQuestion = await _botQuestionRepository.FindByTypeAndOrderNumberAsync(6, 2);
What is the meaning of 6 & 2 here?

2016-12-27 10:32 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +                                            answer.ToLower().ToString());
ToLower already returns string. why do you need to call additional tostring?

2016-12-27 10:32 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +                                                    nextQuestion = await _botQuestionRepository.FindByTypeAndOrderNumberAsync(7, 2);
What does 7 and 2 mean?

2016-12-27 10:32 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +                                            answer.ToLower().ToString());
same mistake repeated here

2016-12-27 10:32 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +                    questionText = string.Format(_stringConstant.ReplyTextForSMTPExceptionErrorMessage, _stringConstant.ErrorOfEmailServiceFailureTaskMail, ex.Message.ToString());
After catching exception. you are not writing log or throwing it. How will the development team know there was exception on server?

2016-12-27 10:32 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
>                  catch (Exception)
Why are you catching generic exception?

2016-12-27 10:32 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +            else if (userRoleAcList.FirstOrDefault(x => x.UserName == user.UserName).Role == _stringConstant.RoleTeamLeader || userRoleAcList.FirstOrDefault(x => x.UserName == user.UserName).Role ==
This code can be improved. it has redundency

2016-12-27 10:32 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +        public async Task<List<TaskMailReportAc>> GetAllEmployeeAsync(string userId)
This method has a lot of repeated code which can be extracted to separate method for better managability

2016-12-27 10:32 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
>              if (taskMails.Count() != 0)
use .Any() instead of .Count()

2016-12-27 10:32 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +        private async Task<List<TaskMailReportAc>> GetTaskMailDetailsInformationAsync(string userId, string role, string userName, string loginId)
This method also has lots of redundant code which can be extracted to a function.

2016-12-27 10:32 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +                    if (taskMailList.Count() != 0)
use .Any() instead of .Count() in entire project

2016-12-27 10:32 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +                DateTime? maxDate = null;
declaration and assignment can be done in single line.

2016-12-27 10:32 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +                        foreach (var taskMailDetail in taskMailDetailList.ToList())
No need to do extra ToList in foreach

2016-12-27 10:32 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +            return taskMailReportAcList;
This is again a very long method with redundant code. it can be improved.

2016-12-27 10:32 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +            return taskMailReportAcList;
Almost all methods in TaskMailRepository is too long and redundant. Please optimize code

2016-12-27 10:32 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
>          string questionText = "";
It should not be used as global

2016-12-28 10:43 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
>          string questionText = "";
ok, i have updated it. And takes as local variable

2016-12-28 10:45 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +                                                nextQuestion = await _botQuestionRepository.FindByTypeAndOrderNumberAsync(6, 2);
It was used for Question order number and Bot Type. Now its taken as enum

2016-12-28 10:45 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +                                                    nextQuestion = await _botQuestionRepository.FindByTypeAndOrderNumberAsync(7, 2);
It was used for Question order number and Bot Type. Now its taken as enum

2016-12-28 10:47 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
>                  catch (Exception)
removed generic exception

2016-12-28 10:47 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +                    questionText = string.Format(_stringConstant.ReplyTextForSMTPExceptionErrorMessage, _stringConstant.ErrorOfEmailServiceFailureTaskMail, ex.Message.ToString());
Added logger.error to print message

2016-12-28 10:47 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +                                            answer.ToLower().ToString());
removed ToString

2016-12-28 10:47 UTC, siddharthashw commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +                                            answer.ToLower().ToString());
removed ToString

2016-12-28 12:56 UTC, iamronakshah commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +        public async Task<List<TaskMailReportAc>> GetAllEmployeeAsync(string userId)
I have removed repeated code. it has been placed in one separated method

2016-12-28 12:56 UTC, iamronakshah commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +            else if (userRoleAcList.FirstOrDefault(x => x.UserName == user.UserName).Role == _stringConstant.RoleTeamLeader || userRoleAcList.FirstOrDefault(x => x.UserName == user.UserName).Role ==
removed this code

2016-12-28 12:56 UTC, iamronakshah commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +        private async Task<List<TaskMailReportAc>> GetTaskMailDetailsInformationAsync(string userId, string role, string userName, string loginId)
I have removed repeated code. it has been placed in one separated method

2016-12-28 12:57 UTC, iamronakshah commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
>              if (taskMails.Count() != 0)
now I have use .Any()  instead of .Count()

2016-12-28 12:57 UTC, iamronakshah commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +                    if (taskMailList.Count() != 0)
now I have use .Any()  instead of .Count()

2016-12-28 12:58 UTC, iamronakshah commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +                        foreach (var taskMailDetail in taskMailDetailList.ToList())
removed ToList

2016-12-28 12:59 UTC, iamronakshah commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +            return taskMailReportAcList;
I have removed repeated code. it has been placed in one separated metho

2016-12-28 12:59 UTC, iamronakshah commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +            return taskMailReportAcList;
I have removed repeated code. it has been placed in one separated metho

2016-12-28 13:24 UTC, iamronakshah commented on Slack.Automation/Promact.Core.Repository/TaskMailRepository/TaskMailRepository.cs
> +                DateTime? maxDate = null;
I did not get this comment.
I know DateTime? maxDate itself contain null but if we have to check it in"if condition" then we have to assign it as null.
Please correct me if i am wrong

2017-01-06 07:36 UTC, chintans approved these changes

2017-01-06 07:37 UTC, merged