Streamline Scrum Repository
Promact/slack-erp-custom-integration-mvc pull request #128
Opened 2016-12-15 08:36 UTC by juliepromact

Fixes#120.

**Files changed are:**

**1. BotQuestionRepository.cs** - Made AddQuestion  awaitable.
**2. IBotQuestionRepository.cs** -  Made AddQuestion  awaitable. Unused usings removed.
**3. Client.cs** - Initialization of _stringConstant rearranged.
**4. OAuthLoginRepository.cs** - Added SaveChangesAsync() .
**5. HttpClientRepository.cs** - Condition updated.
**6. ILeaveRequestRepository.cs** - Updated methods to be awaitable.
**7. LeaveRequestRepository.cs** - Updated methods to be awaitable.
**8. IScrumBotRepository.cs** - Renamed ProcessMessages to ProcessMessagesAsync and updated summary.
**9. ScrumBotRepository.cs** - Streamlined code.
**10. ISlackChannelRepository.cs** - Updated AddSlackChannel to awaitable AddSlackChannelAsync method.
**11. SlackChannelRepository.cs** - Updated AddSlackChannel to awaitable AddSlackChannelAsync method.
**12. SlackRepository.cs** - Updated code after rebase.
**13. ISlackUserRepository.cs** - Added space.
**14. SlackUserRepository.cs** - Made methods awaitable and removed unnecessary usings.
**15. TaskMailRepository.cs** - Used SaveChangesAsync instead of Save()
**16. BotQuestionRepositoryTest.cs** - Updated test cases according to changes in Repository.
**17. LeaveReportRepositoryTest.cs** - Updated test cases according to changes in Repository.
**18. LeaveRequestRepositoryTest.cs** - Updated test cases according to changes in Repository.
**19. OAuthLoginRepositoryTest.cs** - Updated test cases according to changes in Repository.
**20. ScrumBotRepositoryTest.cs** - Updated and added test cases.
**21. ScrumReportRepositoryTest.cs** - Updated test cases to use SaveChangesAsync() instead of Save().
**22. SlackChannelRepositoryTest.cs** - Updated test cases according to changes in Repository.
**23. SlackRepositoryTest.cs** -  Updated test cases to use SaveChangesAsync() instead of Save() and corresponding changes.
**24. SlackUserRepositoryTest.cs** - Test cases added.
**25. TaskMailRepositoryTest.cs** - Updated test cases.
**26. HomeController.cs** - Updated implementation.
**27. LeaveRequestController.cs** - Space added.
**28. OAuthController.cs** - Removed commented code.
**29. EnumApplicationClass.cs** - Added ScrumAnswerStatus.
**30. IRepository.cs** - Removed Save() and added SaveChangesAsync().
**31. Repository.cs** -  Removed Save() and added SaveChangesAsync().
**32. ScrumAnswer.cs** - Added ScrumAnswerStatus property.
**33. IStringConstantRepository.cs** - String constants added.
**34. StringConstantRepository.cs** - String constants added.
**35. Bot.cs** - Removed unnecesary code and Exceptions handled.

2017-01-21 10:32 UTC, chintans requested changes

2017-01-21 10:32 UTC, chintans commented on Slack.Automation/Promact.Erp.DomainModel/Models/TemporaryScrumDetails.cs
> +        //always fetching based on SlackUserId and fetching EmployeeId from user list(which comes from OAuth)
There should not be commented code in source code.

2017-01-21 10:32 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/ScrumRepository/ScrumBotRepository.cs
> +                    replyMessage = string.Format(_stringConstant.GoodDay, slackUserDetailAc.Name) + FetchPreviousDayStatus(firstUser.Id, project.Id, questionList) + question.QuestionStatement + Envir
slackUserDetailAc could potentially throw a NullReferenceException since you are only checking for it's null condition

2017-01-21 10:32 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/ScrumRepository/ScrumBotRepository.cs
> +                        List<ScrumAnswer> scrumAnswer = _scrumAnswerRepository.FetchAsync(x => x.ScrumId == scrum.Id && x.EmployeeId == userDetail.Id).Result.ToList();
scrumAnswer is not used in the block anywhere. What is it's usage?

2017-01-23 09:30 UTC, juliepromact commented on Slack.Automation/Promact.Core.Repository/ScrumRepository/ScrumBotRepository.cs
> +                    replyMessage = string.Format(_stringConstant.GoodDay, slackUserDetailAc.Name) + FetchPreviousDayStatus(firstUser.Id, project.Id, questionList) + question.QuestionStatement + Envir
Yes. Code has been updated to avoid NullReferenceException.

2017-01-23 09:31 UTC, juliepromact commented on Slack.Automation/Promact.Core.Repository/ScrumRepository/ScrumBotRepository.cs
> +                        List<ScrumAnswer> scrumAnswer = _scrumAnswerRepository.FetchAsync(x => x.ScrumId == scrum.Id && x.EmployeeId == userDetail.Id).Result.ToList();
scrumAnswer is not used so it has been removed.

2017-01-23 09:31 UTC, juliepromact commented on Slack.Automation/Promact.Erp.DomainModel/Models/TemporaryScrumDetails.cs
> +        //always fetching based on SlackUserId and fetching EmployeeId from user list(which comes from OAuth)
Commented code has been removed.

2017-01-24 12:32 UTC, chintans approved these changes

2017-01-24 12:32 UTC, merged