Scrum meeting start command changed.
Promact/slack-erp-custom-integration-mvc pull request #140
Opened 2017-01-27 12:07 UTC by juliepromact

Scrum meeting start command changed. Test cases of ScrumBotRepository updated. Fixes#138.

**Files changed are :**

**1. IScrumBotRepository.cs** - scrumBotId parameter passed in ProcessMessagesAsync().
**2. ScrumBotRepository.cs** - Scrum start command changed from _"scrum time"_ to _"start @botname"_.
**3. ScrumBotRepositoryTest.cs** - Corresponding test  cases added and updated.
**4. Bot.cs** - BotId of the bot connected to conduct scrum is obtained and passed as an argument.
**5. EnumApplicationClass.cs** - time replaced by start in ScrumActions.
**6. IStringConstantRepository.cs** - String constants added,
**7. StringConstantRepository.cs** - String constants added,

2017-01-30 14:24 UTC, chintans requested changes

2017-01-30 14:24 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/ScrumRepository/ScrumBotRepository.cs
> +                                await AddAnswerAsync(scrumId, question.Id, expectedUserId, _stringConstant.Leave, ScrumAnswerStatus.Leave);
Here, you can create a collection and save it after foreach loop has completed. It will avoid lots of round trip

2017-01-30 14:24 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/ScrumRepository/ScrumBotRepository.cs
> +            User user = new User();
unnecessary assignment here

2017-01-31 09:40 UTC, juliepromact commented on Slack.Automation/Promact.Core.Repository/ScrumRepository/ScrumBotRepository.cs
> +                                await AddAnswerAsync(scrumId, question.Id, expectedUserId, _stringConstant.Leave, ScrumAnswerStatus.Leave);
Done.

2017-01-31 09:42 UTC, juliepromact commented on Slack.Automation/Promact.Core.Repository/ScrumRepository/ScrumBotRepository.cs
> +            User user = new User();
If I do not assign then I get the following error, "User of unassigned local variable _'user'_"

2017-02-01 10:22 UTC, chintans approved these changes

2017-02-01 10:23 UTC, merged