Environment variable common access
Promact/slack-erp-custom-integration-mvc pull request #57
Opened 2016-10-03 05:47 UTC by juliepromact

Environment variables have been fetched using a common method in a static class(EnvironmentVariableStore) located under Repository project

2016-10-03 07:01 UTC, chintans requested changes
Code is not optimised yet, Single method to access environment variable is too long.

2016-10-03 07:01 UTC, chintans commented on Slack.Automation/Promact.Erp.Util/Email/EmailService.cs
> +                client.Port = Convert.ToInt32(Environment.GetEnvironmentVariable(StringConstant.Port, EnvironmentVariableTarget.Process) );
This still old way of accessing environment variable

2016-10-03 07:01 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/EnvironmentVariableStore.cs
> +            return Environment.GetEnvironmentVariable(VarName, EnvironmentVariableTarget.Process);
This still not optimal. I have to write a lot of code for this.

2016-10-03 09:04 UTC, juliepromact commented on Slack.Automation/Promact.Core.Repository/EnvironmentVariableStore.cs
> +            return Environment.GetEnvironmentVariable(VarName, EnvironmentVariableTarget.Process);
Sir, I did not understand "I have to write a lot of code for this". Please elaborate which code you are referring to ?

2016-10-03 09:47 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/EnvironmentVariableStore.cs
> +            return Environment.GetEnvironmentVariable(VarName, EnvironmentVariableTarget.Process);
It means that code required to access an environment variable is too excess. this could be achieved using less key strokes and less writing.

2016-10-11 12:30 UTC, chintans approved these changes

2016-10-11 12:30 UTC, merged