User and Channel update event handled
Promact/slack-erp-custom-integration-mvc pull request #78
Opened 2016-10-21 08:48 UTC by juliepromact

User and Channel update events handled and update database accordingly. Fixed issue #77 .

Files changed are:

1. IOAuthLoginRepository.cs - Comments added and unnecessary usings removed.
2. OAuthLoginRepository.cs - SlackEventUpdate and SlackChannelAdd methods updated.
3. ISlackUserRepository.cs - UpdateSlackUser method added.
4. SlackUserRepository.cs - UpdateSlackUser method implemented,
5. OAuthController.cs - Handled "channel_rename","user_change" and "group_rename" events.

2016-11-03 09:46 UTC, chintans requested changes

2016-11-03 09:46 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/SlackUserRepository/SlackUserRepository.cs
> +                user.IsAdmin = slackUserDetails.IsAdmin;
why have you not used automapper for assigning values to user class?

2016-11-03 09:46 UTC, chintans commented on Slack.Automation/Promact.Core.Repository/SlackUserRepository/SlackUserRepository.cs
> +            var user = _slackUserDetails.FirstOrDefault(x => x.UserId == slackUserDetails.UserId);
What happens if User is not found? How will you provide feedback to end user?

2016-11-03 09:46 UTC, chintans commented on Slack.Automation/Promact.Erp.Core/Controllers/OAuthController.cs
> +                var errorMessage = string.Format("{0}. Error -> {1}", _stringConstant.LoggerErrorMessageOAuthControllerRefreshToken, ex.ToString());
Why have you used so many try catch in Refresh token method? You are catching a generic exception which we don't do.

2016-11-03 09:46 UTC, chintans commented on Slack.Automation/Promact.Erp.Core/Controllers/OAuthController.cs
> +                var errorMessage = string.Format("{0}. Error -> {1}", _stringConstant.LoggerErrorMessageOAuthControllerSlackEvent, ex.ToString());
here also you are catching a generic exception

2016-11-03 10:16 UTC, juliepromact commented on Slack.Automation/Promact.Core.Repository/SlackUserRepository/SlackUserRepository.cs
> +            var user = _slackUserDetails.FirstOrDefault(x => x.UserId == slackUserDetails.UserId);
We can throw an exception

2016-11-03 10:17 UTC, juliepromact commented on Slack.Automation/Promact.Erp.Core/Controllers/OAuthController.cs
> +                var errorMessage = string.Format("{0}. Error -> {1}", _stringConstant.LoggerErrorMessageOAuthControllerRefreshToken, ex.ToString());
Will change it.

2016-11-03 10:17 UTC, juliepromact commented on Slack.Automation/Promact.Erp.Core/Controllers/OAuthController.cs
> +                var errorMessage = string.Format("{0}. Error -> {1}", _stringConstant.LoggerErrorMessageOAuthControllerSlackEvent, ex.ToString());
Will change it.

2016-11-04 13:11 UTC, juliepromact commented on Slack.Automation/Promact.Core.Repository/SlackUserRepository/SlackUserRepository.cs
> +                user.IsAdmin = slackUserDetails.IsAdmin;
Object structure required is different.

2016-11-08 10:44 UTC, chintans approved these changes

2016-11-08 10:44 UTC, merged